const express=require('express');
const router=express.Router();
const userController=require('../controllers/user_controller');
const { use } = require('bcrypt/promises');
router.post('/signin',userController.signin);
router.post('/signup',userController.signup);
router.post('/addEntry',userController.addEntry);
router.post('/getInfo',userController.getInfo);
router.post('/delEntry',userController.delEntry);
router.post('/addFixed',userController.addFixed);
router.post('/delFixed',userController.delFixed);
router.post('/addPairing',userController.addPairing);
router.post('/delPairing',userController.delPairing);
module.exports=router;